# Generated by Django 3.0.7 on 2020-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
